config/routes.rb
Banking::Application.routes.draw do
  resources :people
  match 'people_house' => 'people#people_house', :as => :people_house

  resources :moves
  match 'acc_moves' => 'moves#acc_moves', :as => :acc_moves
  match 'add_move_alfa' => 'moves#add_move_alfa', :as => :add_move_alfa
  match 'add_move_beta' => 'moves#add_move_beta', :as => :add_move_beta
  match 'add_move_gama' => 'moves#add_move_gama', :as => :add_move_gama
  match 'add_move' => 'moves#add_move', :as => :add_move

  resources :move_types

  resources :accounts
  match 'my_accounts' => 'accounts#my_accounts', :as => :my_accounts
  match 'add_user' => 'accounts#add_user', :as => :add_user
  match 'cash_flow_stat' => 'accounts#cash_flow_stat', :as => :cash_flow_stat
  match 'cf_stat' => 'accounts#cf_stat', :as => :cf_stat

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  match 'change_pass_f' => 'users#change_pass_f', :as => :change_pass_f
  match 'change_pass' => 'users#change_pass', :as => :change_pass
  match 'user_account_list' => 'users#user_account_list', :as => :user_account_list

   root :to => 'accounts#my_accounts'

end

app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessible :user_id, :account_id, :move_type_id, :amount, :date, :person_id, :notice

  belongs_to :user
  belongs_to :account
  belongs_to :move_type

  has_one :person

  scope :mine , lambda {|user| where(:user_id => user)}
  scope :account_moves, lambda {|acc| where(:account_id => acc)}
  scope :acc_moves_by_type, lambda {|mtp| where(:move_type_id => mtp)}
  scope :obydateamount, order("date desc, amount desc")

end

app/models/move_type.rb
class MoveType < ActiveRecord::Base
    attr_accessible :account_id, :name, :income

  belongs_to :account
  has_many :moves

  def income?
    return "+" if self.income
    return "-"
  end

  scope :account_move_types, lambda {|acc| {:conditions => {:account_id => acc}}}
  scope :visible, lambda {|acc| {:conditions => {:account_id => acc}}}

end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def index
    @moves = Move.mine([current_user]).obydateamount.paginate(:per_page => PER_PAGE, :page => params[:page])
  end

  def show
    @move = find_move
  end

  def new
    @move = Move.new
  end

  def create
    @move = Move.new(params[:move].merge(:user_id => current_user))
    if @move.save
      flash[:notice] = "Successfully created move."
      redirect_to acc_moves_url(:acc => params[:move][:account_id])
    else
      render :action => 'new'
    end
  end

  def edit
    @move = find_move
    @account = @move.account
    @amount = hogwartize(@move.amount)
  end

  def update
    @move = find_move
    @move.date = params[:date]
    @move.amount = dehogwartize(params[:amount])
    if @move.save && @move.update_attributes(params[:move])
      flash[:notice] = "Successfully updated move."
      @acc = MoveType.find(params[:move][:move_type_id]).account
      redirect_to acc_moves_url(:acc => @acc)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @move = find_move
    @move.destroy
    flash[:notice] = "Successfully destroyed move."
    redirect_to moves_url
  end
  
  def acc_moves
    if allowed_acc(params[:acc])
      @account = find_account
      if params[:mtp]
        @moves = Move.account_moves([params[:acc]]).acc_moves_by_type([params[:mtp]]).obydateamount.paginate(:per_page => PER_PAGE, :page => params[:page])
      else
        @moves = Move.account_moves([params[:acc]]).obydateamount.paginate(:per_page => PER_PAGE, :page => params[:page])
      end
    else
      notallowed
    end
  end

  def add_move_alfa
    @account = find_account
    @move_types = @account.move_types
  end

  def add_move_beta
    @account = find_account
    @move_type = MoveType.find(params[:move][:move_type_id])
  end

  def add_move_gama
    @move = Move.new
    
    @move.user_id = session[:user_id]
    @move.account_id = params[:acc]
    @move.move_type_id = params[:mt]
    @move.amount = dehogwartize(params[:move][:money])
    @move.date = params[:date]

    if @move.save && @move.update_attributes(params[:move])
      redirect_to acc_moves_url(:acc => params[:acc])
    else
      redirect_to moves_url
    end
  end

private

  def find_move(id = params[:id])
    Move.find(id)
  end

  def find_account(id = params[:acc])
    Account.find(id)
  end

end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= form_for @move do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label 'Account:' %><br />
    <%= @account.name %>
  </p>
  <p>
    <%= f.label :move_type_id %><br />
    <%= collection_select(:move, :move_type_id, @account.move_types, :id, :name)  %>
  </p>
  <p>
    <%= f.label :amount %><br />
    <%= text_field_tag( "amount", @amount ) %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= calendar_date_select_tag "date", @move.date %>
  </p>
  <p>
    <%= f.label :person_id %><br />
    <%= collection_select(:move, :person_id, Person.active.obyname, :id, :whole_name) %>
  </p>
  <p>
    <%= f.label :notice %><br />
    <%= f.text_field :notice %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/moves/_move_fields.html.erb
<tr>
  <td>Amount:</td>
  <td><%= @move_type.income? %>&nbsp;<%= text_field('move', 'money') %></td>
  <td>GAL-SIC-KNU</td>
</tr>
<tr>
  <td>Date:</td>
  <td colspan="2"><%= calendar_date_select_tag 'date', Date.today %></td>
</tr>
<tr>
  <td>Notice:</td>
  <td colspan="2"><%= text_field('move', 'notice') %></td>
</tr>
<tr>
  <td>Person:</td>
  <td colspan="2"><%= collection_select(:move, :person_id, Person.active.obyname, :id, :whole_name)  %></td>
</tr>

app/views/moves/acc_moves.html.erb
<% title "All moves of #{@account.name}" %>

<table class="span-24">
  <tr>
    <th class="span-3">User</th>
    <th class="span-4">Move Type</th>
    <th class="span-2">Amount</th>
    <th class="span-2">Date</th>
    <th class="span-4">Notice</th>
    <th class="span-6">Person</th>
    <th class="span-3"><%= link_to "Add Move", add_move_alfa_path(:acc => @account) %></th>
  </tr>
  <% for move in @moves %>
    <tr>
      <td><%= move.user.username %></td>
      <td><%= move.move_type.name %></td>
      <td><%= hogwartize(move.amount) %></td>
      <td><%= format_date(move.date) %></td>
      <td><%= move.notice %></td>
      <td>
        <% if move.person_id %>
          <%= Person.find(move.person_id).whole_name %>
        <% end %>
      </td>
      <td><%= link_to image_tag("edit.png"), edit_move_path(move) %>&nbsp;&nbsp;<%= link_to image_tag("delete.png"), move, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
    <tr>
      <td colspan="6"><%= will_paginate @moves %></td>
    </tr>
</table>

app/views/moves/add_move_alfa.html.erb
<% title "Add Move 1" %>

<%= form_tag :action => 'add_move_beta', :acc => @account do %>
  <table class="span-7">
    <tr>
      <th class="span-4">Account:</th>
      <th class="span-3"><%= "#{@account.name}" %></th>
    </tr>
    <tr>
      <td>Move type:</td>
      <td><%= collection_select(:move, :move_type_id, @move_types, :id, :name)  %></td>
    </tr>
    <tr>
      <td colspan="2"><%= submit_tag 'Next' %></td>
    </tr>
  </table>
<% end %>

app/views/moves/add_move_beta.html.erb
<% title "Add Move 2" %>

<%= form_tag :action => 'add_move_gama', :acc => @account, :mt => @move_type do %>
  <table class="span-15">
    <tr>
      <th class="span-2">Account:</th>
      <th class="span-3"><%= "#{@account.name}" %></th>
      <th class="span-2"></th>
    </tr>
    <tr>
      <td>Move type:</td>
      <td colspan="2"><%= @move_type.name %></td>
    </tr>
    <%= render 'move_fields' %>
    <tr>
      <td colspan="3"><%= submit_tag 'Next' %></td>
    </tr>
  </table>
<% end %>

app/views/moves/edit.html.erb
<% title "Edit Move" %>

<%= render 'form' %>

<p>
  <%= link_to "View all my moves", moves_path %>
</p>

app/views/moves/index.html.erb
<% title "All moves by #{current_user.username}" %>

<table class="span-20">
  <tr>
    <th class="span-3">Account</th>
    <th class="span-4">Move Type</th>
    <th class="span-1">Amount</th>
    <th class="span-2">Date</th>
<!--    <th>Loan</th>-->
    <th class="span-6">Notice</th>
    <th></th>
  </tr>
  <% for move in @moves %>
    <tr>
      <td><%= Account.find(move.account_id).name %></td>
      <td><%= MoveType.find(move.move_type_id).name %></td>
      <td><%= hogwartize(move.amount) %></td>
      <td><%= format_date(move.date) %></td>
      <!--<td><%= move.loan_id %></td>-->
      <td><%= move.notice %></td>
      <td><%= link_to image_tag("edit.png"), edit_move_path(move) %>&nbsp;&nbsp;<%= link_to image_tag("delete.png"), move, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
    <tr>
      <td colspan="6"><%= will_paginate @moves %></td>
    </tr>
</table>

app/views/moves/new.html.erb
<% title "New Move" %>

<%= render 'form' %>

<p><%= link_to "Back to List", moves_path %></p>

app/views/moves/show.html.erb
<% title "Move" %>

<p>
  <strong>User:</strong>
  <%= @move.user_id %>
</p>
<p>
  <strong>Account:</strong>
  <%= @move.account_id %>
</p>
<p>
  <strong>Move Type:</strong>
  <%= @move.move_type_id %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @move.amount %>
</p>
<p>
  <strong>Date:</strong>
  <%= @move.date %>
</p>
<p>
  <strong>Loan:</strong>
  <%= @move.loan_id %>
</p>
<p>
  <strong>Notice:</strong>
  <%= @move.notice %>
</p>

<p>
  <%= link_to "Edit", edit_move_path(@move) %> |
  <%= link_to "Destroy", @move, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", moves_path %>
</p>