config/routes.rb
Banking::Application.routes.draw do
  resources :people
  match 'people_house' => 'people#people_house', :as => :people_house

  resources :moves
  match 'acc_moves' => 'moves#acc_moves', :as => :acc_moves
  match 'add_move_alfa' => 'moves#add_move_alfa', :as => :add_move_alfa
  match 'add_move_beta' => 'moves#add_move_beta', :as => :add_move_beta
  match 'add_move_gama' => 'moves#add_move_gama', :as => :add_move_gama
  match 'add_move' => 'moves#add_move', :as => :add_move

  resources :move_types

  resources :accounts
  match 'my_accounts' => 'accounts#my_accounts', :as => :my_accounts
  match 'add_user' => 'accounts#add_user', :as => :add_user
  match 'cash_flow_stat' => 'accounts#cash_flow_stat', :as => :cash_flow_stat
  match 'cf_stat' => 'accounts#cf_stat', :as => :cf_stat

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users
  match 'change_pass_f' => 'users#change_pass_f', :as => :change_pass_f
  match 'change_pass' => 'users#change_pass', :as => :change_pass
  match 'user_account_list' => 'users#user_account_list', :as => :user_account_list

   root :to => 'accounts#my_accounts'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<div id="pataStranky">
  <a href="mailto:janekaren@soukroma.cz">Write to admin</a><br />
  Banking&nbsp;&nbsp;<%=format_date_time(Time.now) -%>
</div>

app/views/layouts/_header.html.erb
<div class="nav">
  <ul class="Banking Bankingm">

    <li class="Bankingi"><a><%= current_user.username %></a>
      <ul class="Bankingm">
        <li class="Bankingi"><%= link_to 'Change password', change_pass_f_url %></li>
      </ul>
    </li>

    <li class="Bankingi"><%= link_to 'My accounts', my_accounts_url %></li>

    <li class="Bankingi"><a class="Bankingi" href="#"><span>Move types</span></a>
      <ul class="Bankingm">
        <% for acc in current_user.accounts do %>
          <li class="Bankingi"><%= link_to acc.name, move_types_url(:acc => acc.id) %></li>
        <% end %>
      </ul>
    </li>
    
    <li class="Bankingi"><a class="Bankingi" href="#"><span>Moves</span></a>
      <ul class="Bankingm">
        <li class="Bankingi"><%= link_to 'All my moves', moves_url %>
          <% for acc in current_user.accounts do %>
            <li class="Bankingi"><span><%= link_to acc.name, acc_moves_url(:acc => acc.id) %></span>
              <ul class="Bankingm">
                <% for mtp in acc.move_types do %>
                  <li class="Bankingi"><%= link_to mtp.name, acc_moves_url(:acc => acc.id, :mtp => mtp.id) %>
                <% end %>
              </ul>
            </li>
          <% end %>
        </li>
      </ul>
    </li>

    <li class="Bankingi"><a><span>Statistics</span></a>
      <ul class="Bankingm">
        <li class="Bankingi"><%= link_to 'Cash flow', cash_flow_stat_url %></li>
      </ul>
    </li>
    
    <li class="Bankingi"><a><span>People</span></a>
      <ul class="Bankingm">
        <li class="Bankingi"><span><%= link_to 'List', people_url %></span>
          <ul class="Bankingm">
            <% for house in Person.select('DISTINCT house') do %>
              <li class="Bankingi"><%= link_to house.house, people_house_url(:house => house.house) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </li>
    
<% if current_user.admin? %>
    <li class="Bankingi"><a class="Bankingi" href="#"><span>Administration</span></a>
      <ul class="Bankingm">
        <li class="Bankingi"><%= link_to 'Users', users_url %></li>
        <li class="Bankingi"><%= link_to 'Accounts', accounts_url %></li>
        <li class="Bankingi"><%= link_to 'User/Accounts',  user_account_list_url %></li>
      </ul>
    </li>
<% end %>

    <li class="Bankingi"><%= link_to 'Logout', :controller => 'sessions', :action => 'destroy' %></li>

  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Banking" %></title>
    <%= stylesheet_link_tag "blueprint/screen" -%>
    <%= stylesheet_link_tag "menu_style" %>
    <%= stylesheet_link_tag "calendar_date_select/plain" %>
    <%= stylesheet_link_tag "banking" %>
    <%= javascript_include_tag :defaults %>
    <%= calendar_date_select_includes %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div>
      <% if current_user -%>
        <%= render :partial => '/layouts/header' -%>
      <% end -%>
    </div>

    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>

    <% if current_user -%>
      <%= render :partial => '/layouts/footer' -%>
    <% end -%>

  </body>
</html>